### ISSUE TITLE
Magento crashing when trying to get all payment-methods

### ISSUE THREAD

**Issue by nniecws** [wirecard/magento-ee#63]
I have a big problem by trying to get all available payment-methods in Magento by using this method:
```
$allAvailablePaymentMethods = Mage::getModel('payment/config')->getAllMethods();
```
Magento crashes with the following error: 

PHP Fatal error:  Class 'Wirecard\PaymentSdk\Transaction\PayPalTransaction' not found in .../app/code/core/Mage/Core/Model/Config.php on line 1354

The class PayPalTransaction can not be found in WirecardEE_PaymentGateway_Model_Paypal used in
```
 protected $_paymentMethod = PayPalTransaction::NAME;
```
If i change **PayPalTransaction::NAME** to **'paypal'** then it works, but also other classes have the same issue. I think that the libraries are not correctly included.

**Comment by serucee** [comment]
Hi,

thank you for your feedback. We will look into the described issue and keep you updated.

Best regards,
Wirecard Shop Systems Team

**Comment by charly06** [comment]
I get the same message. Just updated a Magento 1 EE installation to the latest Magento 1 EE version and used this WirecardEE extension v1.2.3 for a customer.

**Comment by charly06** [comment]
Well, thanks to Wirecard Support I was able to solve the issue.

The error occurs because the origin of the call is a custom shell script which extends Mage_Shell_Abstract. The mentioned class is only loaded if a request comes from fronted and results in  `app/code/core/Mage/Core/Controller/Varien/Front.php` dispatching the event `controller_front_init_before`. This event triggers the necessary autoload call of lib/WirecardEE/vendor/autoload.php in order to load all Wirecard transaction classes.

For the Wirecard Checkout Page extension a similar issue was reported quite a while ago (https://github.com/wirecard/magento-wcp/issues/8#issue-193870257).

I was able to solve the issue by dispatching a new custom event in my extension just some time before the transaction classes are expected. 

`Mage::dispatchEvent('isl_worker_export_order_before');`

Then I added this new custom event to the `config.xml` of the WirecardEE module (quite ugly since it's not update safe, but I dont know a more elegant solution)

```
<events>
...
  <isl_worker_export_order_before>
    <observers>
      <wirecard_ee_composer_autoload>
        <type>singleton</type>
        <class>paymentgateway/observer</class>
        <method>controllerFrontInitBefore</method>
      </wirecard_ee_composer_autoload>
    </observers>
  </isl_worker_export_order_before>

</events>
```

@serucee you may think about either calling the autoload.php of your package in the lib folder for backend tasks as well. Unfortunately, I didnt find a proper Magento Core event for it. Alternatively, please add to your documentation that in order to process orders from sources other than frontend requests, users need to call the autoload.php of your lib first. Since your old plugin Wirecard Checkout Page didnt have a lib package, I didnt consider this in my custom extension.

**Comment by serucee** [comment]
Hi @charly06 

I'm happy that our support was able to help you! Thank you for the extended investigation, we will look into it as soon as possible and keep you updated!

Best regards,
Wirecard Shop Systems Team

**Comment by serucee** [comment]
Hi @charly06  ,
Hi @nniecws 

we are going to release version 1.3.1 in the course of the next week which will resolve this issue. It will contain the suggested solution by @charly06 and add it to our documentation. I am sorry for the delay.

Best regards,
Wirecard Shop Systems Team

**Comment by serucee** [comment]
Hi @charly06 ,
@nniecws ,

the current release (1.3.1) resolves this issue with the suggested solution by @charly06 , thanks again for your suggestion!

Best regards,
Wirecard Shop Systems Team
